version: '3.8'

services:
  effward-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: $DATABASE_URL
    environment:
      - DATABASE_URL
    ports:
      - "8080:8080"
    networks:
      - effward-network

networks:
  effward-network:
