# fly.toml app configuration file generated for effward-dev on 2023-04-26T15:06:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "effward-dev"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"
  build-target = "builder"

[deploy]
  strategy = "immediate"

[env]
  EFFWARD_DEV_ENVIRONMENT = "production"
  RUST_LOG = "info"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 5000
    soft_limit = 3500
  [checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "1s"
    path = "/health"
    protocol = "https"
